### ISSUE TITLE
emmm……

### ISSUE THREAD

**Issue by shkey** [ithou/Scores-Spider#1]
学校的垃圾小水管服务器你还每三分钟请求一次，能不能饶过它😂
另外你的代码有好几处还可以优化下

**Comment by ithou** [comment]
（我这破东西也有人看也是烧高香了🤣）哈哈，真的是小水管，教务系统不知道为啥已经挂了💔 ～ 我刚学Python不久，写的第一个东西，肯定有很多不足，恳请斧正！
